language: go
go:
  - '1.15'
services:
  - docker
script:
  - docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
after_script:
  # log test results
  - docker cp go-lab2_test_1:/go/src/practice/out/integration-tests logs
  - ls logs
  - cat logs/bood_test
