FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

# TODO: Змініть на власну реалізацію системи збірки
RUN go get github.com/ReallyGreatBand/lab-2.1/build/cmd/bood

WORKDIR /go/src/practice-2
COPY . .

# TODO: Замініть на запуск bood, який призводить до виконання інтеграційних тестів.
ENTRYPOINT ["bood", "out/integration-tests/bood_test"]
